version: 0.0.1.{build}-test

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAURL: http://www.lua.org/ftp
  LUAROCKS_URL: http://keplerproject.github.io/luarocks/releases
  LUAROCKS_REPO: http://rocks.moonscript.org
  LUAROCKS_VER: 2.2.1
  LUAROCKS_SHORTV: 2.2

  # if you need to install luarocks to a different directory
  # If you change this, update 'cache' entry
  LUAROCKS_INSTALL: C:\Program Files (x86)\LuaRocks

  # External dependencies
  LR_EXTERNAL: c:\external


  #LUA: the Lua interpreter. either Lua or LuaJIT

  SEVENZIP: 7z

  matrix:
  - LUA_VER: 5.1.5
    LUA_SHORTV: 5.1
    LUA: lua

  - LUA_VER: 5.2.4
    LUA_SHORTV: 5.2
    LUA: lua

  - LUA_VER: 5.3.0
    LUA_SHORTV: 5.3
    LUA: lua

  - LJ_VER: 2.0.3
    LUA_SHORTV: 5.1
    LJ_SHORTV: 2.0
    LUA: luajit

  - LJ_VER: 2.1
    LUA_SHORTV: 5.1
    LJ_SHORTV: 2.1
    LUA: luajit

platform:
  - x86
  - x64

cache:
  - c:\lua5.1.5 -> appveyor.yml
  - c:\lua5.2.4 -> appveyor.yml
  - c:\lua5.3.0 -> appveyor.yml
  - c:\lj2.0 -> appveyor.yml
  - c:\lj2.1 -> appveyor.yml
  - c:\external -> appveyor.yml
  - C:\Program Files (x86)\LuaRocks -> appveyor.yml
  - C:\Program Files\LuaRocks -> appveyor.yml

init:
# Setup Lua development/build environment
# Make VS 2013 command line tools available
- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

install:
# Setup Lua development/build environment
- call .appveyor\install.bat

before_build:
# @todo
- echo "Installing external deps"

build_script:
- luarocks make rockspecs/foo-scm-0.rockspec

before_test:
# install test only deps
- luarocks install telescope

test_script:
- echo "Testing..."
- cd %APPVEYOR_BUILD_FOLDER%\test
- tsc.bat test.lua

after_test:
# @todo
