version: 0.0.1.{build}-test

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAURL: http://www.lua.org/ftp
  LUAROCKS_URL: http://keplerproject.github.io/luarocks/releases
  LUAROCKS_REPO: http://rocks.moonscript.org
  LUAROCKS_VER: 2.2.1

  matrix:
  - LUA_VER: 5.3.0
    LUA_SHORTV: 5.3

  - LUA_VER: 5.2.4
    LUA_SHORTV: 5.2

  - LUA_VER: 5.1.5
    LUA_SHORTV: 5.1


init:
# Make VS 2013 command line tools available
- '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%'

install:
- cd %APPVEYOR_BUILD_FOLDER%
- call .appveyor\install.bat

build_script:
- cd %APPVEYOR_BUILD_FOLDER%
- call .appveyor\build.bat

test_script:
- cd %APPVEYOR_BUILD_FOLDER%\test
- lunit test.lua
