version: 0.0.1.{build}-test

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAURL: http://www.lua.org/ftp
  LUAROCKS_URL: http://keplerproject.github.io/luarocks/releases
  LUAROCKS_REPO: http://rocks.moonscript.org
  LUAROCKS_VER: 2.2.1
  LUAROCKS_SHORTV: 2.2

  matrix:
  - LUA_VER: 5.1.5
    LUA_SHORTV: 5.1

  # - LUA_VER: 5.2.4
  #   LUA_SHORTV: 5.2

  # - LUA_VER: 5.3.0
  #   LUA_SHORTV: 5.3

install:
# Setup Lua development/build environment
- call .appveyor\install.bat

before_build:
# @todo
- echo "Installing external deps"

build_script:
- luarocks make rockspecs/foo-scm-0.rockspec

before_test:
# install test only deps
- luarocks install telescope

test_script:
- echo "Testing..."
- cd %APPVEYOR_BUILD_FOLDER%\test
- tsc test.lua
